# Data paths relative to project root
raw_path: "data/raw"
processed_path: "data/processed"
shap_path: "data/processed/shap"
figs_path: "data/processed/figs"

# Specific data files
raw_files:
  transactions: "data/raw/SilvioKlein_Transactions.rdata"
  shapefile: "data/raw/PCODE_2024_PT.shp"
  provinces_map: data/raw/provincies_2025.geojson
  nuts3_map: data/raw/coropgebied_2025.geojson
  mortgage_rate: data/raw/nld_mortgage_rate.csv
  systemic_stress: data/raw/nld_systemic_stress.csv
  unemloyment_rate: data/raw/nld_unemployment.csv
  processed_data: data/processed/processed_data.parquet
  preprocessed_data: data/processed/preprocessed_data.parquet